function [barcode_syn,barcode_rec,a,m0,splitPoints]=generate_mix(k,num_strain)
rng(k)
splitPoints = sort(randperm(num_strain-1, 2));
barcode_syn = [];
barcode_rec = [];
a = [];
m0 = [];

cheating = load('result_clusterserver/ecology_figure1_cheating_3.mat'...
    ,'barcode_syn_record','barcode_rec_record','a_record','m0_record');
pure = load('result_clusterserver/ecology_figure1_pure_3.mat'...
    ,'barcode_syn_record','barcode_rec_record','a_record','m0_record');
partial = load('result_clusterserver/ecology_figure1_partial_3.mat'...
    ,'barcode_syn_record','barcode_rec_record','a_record','m0_record');
barcode_syn = [cheating.barcode_syn_record(:,1:splitPoints(1),k),...
    pure.barcode_syn_record(:,splitPoints(1)+1:splitPoints(2),k),...
    partial.barcode_syn_record(:,splitPoints(2)+1:num_strain,k)];
barcode_rec = [cheating.barcode_rec_record(:,1:splitPoints(1),k),...
               pure.barcode_rec_record(:,splitPoints(1)+1:splitPoints(2),k),...
               partial.barcode_rec_record(:,splitPoints(2)+1:num_strain,k)];
a = [cheating.a_record(k,1:splitPoints(1)),...
    pure.a_record(k,splitPoints(1)+1:splitPoints(2)),...
    partial.a_record(k,splitPoints(2)+1:num_strain)];
m0 = [cheating.m0_record(k,1:splitPoints(1)),...
    pure.m0_record(k,splitPoints(1)+1:splitPoints(2)),...
    partial.m0_record(k,splitPoints(2)+1:num_strain)];

a = [a;1-a];
end