function [barcode_syn,barcode_rec,a,m0,community_name,splitPoints]=generate_mix_invasion_2component(k,num_strain,community1,community2,invader)
rng(k)
splitPoints = sort(randperm(num_strain-2, 1));

barcode_syn = [community1.barcode_syn_record(:,1:splitPoints,k),...
               community2.barcode_syn_record(:,splitPoints+1:num_strain-1,k),...
               invader.barcode_syn_record(:,num_strain,k)];
barcode_rec = [community1.barcode_rec_record(:,1:splitPoints,k),...
               community2.barcode_rec_record(:,splitPoints+1:num_strain-1,k),...
               invader.barcode_rec_record(:,num_strain,k)];
a = [community1.a_record(k,1:splitPoints),...
     community2.a_record(k,splitPoints+1:num_strain-1),...
     invader.a_record(k,num_strain)];
m0 = [community1.m0_record(k,1:splitPoints),...
     community2.m0_record(k,splitPoints+1:num_strain-1),...
     invader.m0_record(k,num_strain)];
a = [a;1-a];
community_name=[inputname(5) '_invade_mix'];
end